version: '3.6'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./provision:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"


  postgresql:
    image: postgres:11
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_PORT: 5432
      PGDATA: /pgdata
    ports: ["5432:5432"]


volumes:
  mysql-data:
    driver: local
